# Ruff configuration for MiniGPT
# Fast Python linter and formatter

line-length = 100
target-version = "py38"

[lint]
# Select specific rule sets
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "N",    # pep8-naming
    "S",    # bandit security
    "T20",  # flake8-print
    "W",    # pycodestyle warnings
]

# Ignore specific rules
ignore = [
    "E501",  # line too long (handled by formatter)
    "S101",  # assert usage (ok in tests)
    "T201",  # print statements (ok in demos)
    "B008",  # do not perform function calls in argument defaults
    "S105",  # possible hardcoded password (false positive for token constants)
]

# Exclude directories
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    "build",
    "dist",
    "*.egg-info",
]

# Per-file ignores
[lint.per-file-ignores]
"tests/*" = ["S101", "T201"]  # Allow assert and print in tests
"examples/*" = ["T201"]       # Allow print in examples
